### ISSUE TITLE
Git: Another way to get the current branch

### ISSUE THREAD

**Issue by AntoineCezar** [sdball/dotfiles#7]
https://github.com/sdball/dotfiles/blob/df5fcbeec05dee67bb0bea72592ccfdcf473e625/bin/git-outgoing#L7
You can use `git rev-parse --abbrev-ref HEAD` to get the branch name without using grep|tr

**Comment by sdball** [comment]
Oh nice! Sorry I didn't even notice this open issue until now 😭

**Comment by AntoineCezar** [comment]
I'm also pretty slow to fetch my github messages ^_^
